name: AireMonterrey

on:
  schedule:
    - cron: "0 12-23 * * *"   # 6:00 AM a 5:00 PM México (12–23 UTC)
    - cron: "0 0-2 * * *"     # 6:00 PM a 8:00 PM México (0–2 UTC)
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: List files in repo (debug)
      run: |
        pwd
        ls -R

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install pandas requests

    # ----------------------------------------------------------
    # 1) Ejecutar main.py (ETL IMKTodo11 → aire_monterrey.csv)
    # ----------------------------------------------------------
    - name: Run main ETL script
      run: python main.py

    # ----------------------------------------------------------
    # 2) Ejecutar indice_api_ancho.py
    #    (API índice por estación → ancho + histórico)
    # ----------------------------------------------------------
    - name: Run indice API ancho script
      run: python indice_api_ancho.py

    # ----------------------------------------------------------
    # 3) Ejecutar alertas.py (usa aire_monterrey.csv recién creado)
    # ----------------------------------------------------------
   # - name: Run alert script
   #   if: success()
   #   env:
   #     SMTP_USER: ${{ secrets.SMTP_USER }}
   #     SMTP_PASS: ${{ secrets.SMTP_PASS }}
   #     ALERT_TO_EMAIL: ${{ secrets.ALERT_TO_EMAIL }}
   #   run: python alertas.py

    # ----------------------------------------------------------
    # 4) Commit y push de los CSV actualizados
    # ----------------------------------------------------------
    - name: Commit CSV update
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add *.csv
        git commit -m "Auto update" || echo "No changes to commit"
        git push
