name: AireMonterrey

on:
  schedule:
    - cron: "30 16 * * *"   # 10:30 AM México (UTC-6)
    - cron: "30 20 * * *"   # 2:30 PM México (UTC-6)
    - cron: "30 1 * * *"    # 7:30 PM México (UTC-6) → 01:30 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install pandas requests

    - name: Run script
      run: python main.py      # ← AQUI el cambio importante

    - name: Commit CSV update
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add aire_monterrey.csv
        git commit -m "Auto update"
        git push
